Repository catenax-eV/catenax-ev.github.io, pull requests merged in 2024-10, with the labels that each got.

#123 doc(release-management): add timeline for 25.03
  docusaurus.config.ts
  src/pages/timelines.md
  static/img/cx-timeline-24.12.png
  static/img/cx-timeline-25.03.png
  static/img/cx-timeline-overview.png
Labels: documentation

#130 chore(upgrade libs): update dependencies/libs
  package-lock.json
Labels: enhancement

#143 Docs/Update timelines
  src/pages/timelines.md
  static/img/cx-timeline-24.12.png
  static/img/cx-timeline-25.03.png
Labels: documentation

#142 fix(versioned-links): adapt all links to match versioning strategy
  docs/operating-model/how-data-space-governance/how-data-space-governance.md
  docs/operating-model/how-data-space-operations/how-data-space-operations.md
  docs/regulatory-framework/10000ft/data-exchange-contracts.md
  docs/regulatory-framework/governance-framework.md
  docs/standards/CX-0002-DigitalTwinsInCatenaX/CX-0002-DigitalTwinsInCatenaX.md
  docs/standards/CX-0018-DataspaceConnectivity/CX-0018-DataspaceConnectivity.md
  docs/standards/CX-0053-BPNDiscoveryServiceAPIs/CX-0053-BPNDiscoveryServiceAPIs.md
  docs/standards/CX-0131-CircularityCore/CX-0131-CircularityCore.md
  docs/standards/CX-0135-CompanyCertificateManagement/CX-0135-CompanyCertificateManagement.md
  docs/standards/CX-0136-UseCasePCF/CX-0136-UseCasePCF.md
  docs/standards/CX-0143-UseCaseCircularEconomyDigitalProductPassportStandard/CX-0143-SEM.md
  docs/working-model/ecosystem/ecosystem.md
  docs/working-model/overview.md
  docusaurus.config.ts
  versioned_docs/version-24.03/certification/certification/certification.md
  versioned_docs/version-24.03/operating-model/how-data-space-governance/how-data-space-governance.md
  versioned_docs/version-24.03/standards/CX-0002-DigitalTwinsInCatenaX/CX-0002-DigitalTwinsinCatenaX.md
  versioned_docs/version-24.03/standards/CX-0084-FederatedQueriesInDataSpaces/CX-0084-FederatedQueriesInDataSpaces.md
  versioned_docs/version-24.03/working-model/overview.md
  versioned_docs/version-Jupiter/operating-model/how-data-space-governance/how-data-space-governance.md
  versioned_docs/version-Jupiter/operating-model/how-data-space-operations/how-data-space-operations.md
  versioned_docs/version-Jupiter/regulatory-framework/10000ft/data-exchange-contracts.md
  versioned_docs/version-Jupiter/regulatory-framework/governance-framework.md
  versioned_docs/version-Jupiter/standards/CX-0002-DigitalTwinsInCatenaX/CX-0002-DigitalTwinsInCatenaX.md
  versioned_docs/version-Jupiter/standards/CX-0018-DataspaceConnectivity/CX-0018-DataspaceConnectivity.md
  versioned_docs/version-Jupiter/standards/CX-0053-BPNDiscoveryServiceAPIs/CX-0053-BPNDiscoveryServiceAPIs.md
  versioned_docs/version-Jupiter/standards/CX-0084-FederatedQueriesInDataSpaces/CX-0084-FederatedQueriesInDataSpaces.md
  versioned_docs/version-Jupiter/standards/CX-0131-CircularityCore/CX-0131-CircularityCore.md
  versioned_docs/version-Jupiter/standards/CX-0135-CompanyCertificateManagement/CX-0135-CompanyCertificateManagement.md
  versioned_docs/version-Jupiter/standards/CX-0136-UseCasePCF/CX-0136-UseCasePCF.md
  versioned_docs/version-Jupiter/standards/CX-0143-UseCaseCircularEconomyDigitalProductPassportStandard/CX-0143-SEM.md
  versioned_docs/version-Jupiter/working-model/ecosystem/ecosystem.md
  versioned_docs/version-Jupiter/working-model/overview.md
Labels: bug
